/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY HERO-I/O DOCS.

	Synopsis	: Gets an app from its _id
	Method		: GET
	Path		: /app/:appId

	Num Params		: 1

	req.params.appId			: The _id key of the app

END OF AUTOMATICALLY GENERATED BY HERO-I/O DOCS.___*/

var qlog = require('../qlog.js')
;

module.exports = function (req, res, next){

	qlog.app.getById ( 
		req.params.appId
	, 
		function (err, data){
			if ( err ) {
				console.log( err );
				res.writeHead(500);
				res.end();
			}
			else {
				res.writeHead(200);
				res.end( JSON.stringify(data) );
			}
		}
	);

};