/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Updates an app
	Method		: POST
	Path		: /app/:appId

	Num Params		: 3

	req.params.appId			: The _id key of the app
	req.body.n			: New application Name (empty for no changes)
	req.body.cb			: New callback Url (empty for no changes)

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/

var qlog = require('../qlog.js')
;

module.exports = function (req, res, next){

	qlog.app.update(
		req.params.appId
	, 	req.body.n
	, 	req.body.cb
	, 
		function (err){
			if ( err ) {
				console.log( err );
				res.writeHead(500);
			}
			else {
				res.writeHead(200);
			}
			res.end();
		}
	);

};
