/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Renews the secretKey
	Method		: POST
	Path		: /app/:appId/resetkey

	Num Params		: 1

	req.params.appId			: The _id key of the app

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/

var qlog = require('../qlog.js')
;

module.exports = function (req, res, next){

	qlog.app.refreshSecretKey(
		req.params.appId
	,
		function (err, data){
			if ( err ) {
				console.log( err );
				res.writeHead(500);
				res.end();
			}
			else {
				res.writeHead(200);
				res.end( JSON.stringify({ secretKey : data.secretKey }) );
			}
		}
	);

};
