/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY HERO-I/O DOCS.

	Synopsis	: Delete an app
	Method		: DELETE
	Path		: /app/:appId

	Num Params		: 1

	req.params.appId			: The _id key of the app

END OF AUTOMATICALLY GENERATED BY HERO-I/O DOCS.___*/

var qlog = require('../qlog.js')
;

module.exports = function (req, res, next){

	qlog.app.erase(
		req.params.appId
	, 
		function (err){
			if ( err ) {
				console.log( err );
				res.writeHead(500);
			}
			else {
				res.writeHead(200);
			}
			res.end();
		}
	);

};