/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Adds a log to an application
	Method		: PUT
	Path		: /app/:appId/log

	Num Params		: 5

	req.params.appId			: The clientId of the app
	req.body.secretKey			: The secretKey of the app
	req.body.msg			: The log message
	req.body.time			: The date/time when the record was created
	req.body.tags			: A list of comma-separated tags associated with the application

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/

var qlog = require('../qlog.js')
;

module.exports = function (req, res, next){

	// json payload -> { 'msg' : 'An error occurs', 'tags' : 'pro,dev,chrome,ff,iOS,...', 'time':1234567890, secretKey:'...' }

	qlog.app.getByClientId(req.params.appId, function(err, data){
		if(data === null){
			res.writeHead(400);
			res.end('Bad request');
		} else {
			if(data.secretKey === req.body.secretKey){
				var tags = req.body.tags;
				if(tags === undefined || tags === null) {
					tags = '';
				}

				qlog.log.create(req.params.appId, req.body.msg, req.body.time, tags, function (err, data){
					if ( err ) {
						console.log( err );
						res.writeHead(500);
					}
					else {
						res.writeHead(200);
					}
					res.end('');
				});
			} else {
				res.writeHead(401);
				res.end('Unauthorized');
			}
		}
	});
};
