/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY HERO-I/O DOCS.

	Synopsis	: Gets the logs from application
	Method		: GET
	Path		: /app/:appId/log

	Num Params		: 2

	req.params.appId			: The clientId of the app
	req.headers.Cookie			: The pastry.sid of the connected user ( example: pastry.sid=d416fc67-07c6-406b-a393-c86fd54ee361 )

END OF AUTOMATICALLY GENERATED BY HERO-I/O DOCS.___*/

var qlog = require('../qlog.js')
;

module.exports = function (req, res, next){

	if ( !req.pastry.data.uid ) {
		res.writeHead(401);
		res.end();
	}
	else {
		qlog.log.getByApp(
			req.params.appId
		,
			{ 'uid' : req.pastry.data.uid
			// , 'page'  : req.params('p')
			// , 'count' : req.params('c')
			}
		,
			function (err, data){
				if ( err ) {
					res.writeHead(500);
					res.end(JSON.stringify(err));
				}
				else {
					res.writeHead(200);
					res.end(JSON.stringify(data));
				}
			}
		);
	}

}
