/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Disconnects an user from QLog
	Method		: POST
	Path		: /signout

	Num Params		: 0


END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/

var qlog = require('../qlog.js')
;

module.exports = function (req, res, next){

	req.pastry.invalidate();
	res.writeHead(200);
	res.end();

}
