/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Gets all users from QLog
	Method		: GET
	Path		: /user

	Num Params		: 1

	req.headers.Cookie			: The pastry.sid of the connected admin user ( example: pastry.sid=d416fc67-07c6-406b-a393-c86fd54ee361 )

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/

var qlog = require('../qlog.js')
;

module.exports = function (req, res, next){

	if(req.pastry.data.uid === undefined || !req.pastry.data.isAdmin){
		console.log( req.pastry.data );
		res.writeHead(401);
		res.write('');
		res.end();
		return;
	}

	qlog.user.getUsers(
		{
			// 'uid' : req.pastry.data.uid,
			// 'page'  : req.params('p'),
			// 'count' : req.params('c')
		},

		function (err, data){
			if ( err ) {
				console.log(err);
				res.writeHead(500);
				res.write( JSON.stringify(err) );
			}
			else {
				res.writeHead(200);
				res.write( JSON.stringify(data) );
			}
			res.end();
		}
	);

};
