/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY HERO-I/O DOCS.

	Synopsis	: Gets the information of the connected user
	Method		: GET
	Path		: /user/me

	Num Params		: 1

	req.headers.Cookie			: The pastry.sid of the connected user ( example: pastry.sid=d416fc67-07c6-406b-a393-c86fd54ee361 )

END OF AUTOMATICALLY GENERATED BY HERO-I/O DOCS.___*/

var qlog = require('../qlog.js');

module.exports = function (req, res, next){

	if(req.pastry.data.uid === undefined){
		res.writeHead(401);
		res.write('');
		res.end();
		return;
	}

	qlog.user.getUserById( 
		req.pastry.data.uid
	,
		function (err, data){
			if ( err || data === null ) {
console.log('user_me_get', err, data);
				res.writeHead(500);
				res.write( JSON.stringify(err) );
			}
			else {
				res.writeHead(200);
				res.write( JSON.stringify(data) );
			}
			res.end();
		}
	);

};
