/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Gets an app from its _id
	Method		: GET
	Path		: /app/:appId

	Num Params		: 1

	req.params.appId			: The _id key of the app

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/