/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Returns the RabbitMQ URL and the exchange identifier of the app
	Method		: POST
	Path		: /app/:appId/getcredential

	Num Params		: 2

	req.params.appId			: The clientId of the app
	req.body.p			: The secretKey of the app

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/