/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Updates an app
	Method		: POST
	Path		: /app/:appId

	Num Params		: 3

	req.params.appId			: The _id key of the app
	req.body.n			: New application Name (empty for no changes)
	req.body.cb			: New callback Url (empty for no changes)

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/