/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Creates a new app
	Method		: PUT
	Path		: /app

	Num Params		: 3

	req.body.n			: Application Name
	req.body.cb			: Callback Url
	req.readers.Cookie			: The pastry.sid of the connected user ( example: pastry.sid=d416fc67-07c6-406b-a393-c86fd54ee361 )

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/