/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Renews the secretKey
	Method		: POST
	Path		: /app/:appId/resetkey

	Num Params		: 1

	req.params.appId			: The _id key of the app

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/