/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Adds a log to an application
	Method		: PUT
	Path		: /app/:appId/log

	Num Params		: 5

	req.params.appId			: The clientId of the app
	req.body.secretKey			: The secretKey of the app
	req.body.msg			: The log message
	req.body.time			: The date/time when the record was created
	req.body.tags			: A list of comma-separated tags associated with the application

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/