/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Disconnects an user from QLog
	Method		: POST
	Path		: /signout

	Num Params		: 0


END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/