/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Creates a new QLog user
	Method		: POST
	Path		: /signup

	Num Params		: 2

	req.body.e			: user email
	req.body.p			: user password

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/