/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Connects an user to QLog
	Method		: POST
	Path		: /signin

	Num Params		: 2

	req.body.e			: user email
	req.body.p			: user password

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/