/**___ DO NOT MODIFY. AUTOMATICALLY GENERATED BY RESTRUC FROM I/O Docs.

	Synopsis	: Gets the information of the connected user
	Method		: GET
	Path		: /user/me

	Num Params		: 1

	req.readers.Cookie			: The pastry.sid of the connected user ( example: pastry.sid=d416fc67-07c6-406b-a393-c86fd54ee361 )

END OF AUTOMATICALLY GENERATED BY RESTRUC.___*/